@Library('pdehnel-sharedlib@feature/devon4j')

//Sharedlibrary configuration
import com.capgemini.productionline.configuration.*
Jenkins jenkinsConfiguration = new Jenkins();
GitLab gitlabConfiguration = new GitLab(this, params.GITLAB_USER_PRIVATE_TOKEN);


pipeline {
    agent any
    
    //Jenkins Job Parameters
    parameters { 
        string(name: 'GITLAB_USER_PRIVATE_TOKEN', defaultValue: '', description: 'NEEDS TO BE SET!. Private Token of a Production Line Gitlab User that can be used to create repositories.') 
        string(name: 'GITLAB_CREATE_GROUP_NAME', defaultValue: 'devon', description: 'Private Token of a Production Line Gitlab User that can be used to create repositories.') 
        string(name: 'GITLAB_CREATE_PROJECT_NAME', defaultValue: 'MyThaiStar', description: 'Private Token of a Production Line Gitlab User that can be used to create repositories.') 
        string(name: 'GITLAB_CREATE_BRANCH', defaultValue: 'master', description: 'Private Token of a Production Line Gitlab User that can be used to create repositories.') 
        string(name: 'GITLAB_CREATE_PROJECT_DESCRIPTION', defaultValue: 'MyThaiStar Sample Devon4J application', description: 'Private Token of a Production Line Gitlab User that can be used to create repositories.') 

    }
    
    stages {
        stage('PL preparation') {
            steps{
                //Create a new repository for MyThaiStar inside the Production Line
                gitlabConfiguration.createProject(params.GITLAB_CREATE_GROUP_NAME, params.GITLAB_CREATE_PROJECT_NAME, "test", params.GITLAB_CREATE_PROJECT_DESCRIPTION, params.GITLAB_CREATE_BRANCH)

            }
        }

        stage('Clone MyThaiStar to PL'){
            steps{
                print "test"
            }
        }

        stage('Generate build and deploy jobs in Jenkins'){
            steps{
                print "test"
            }
        }
    }
}